---
kind: pipeline
type: docker
name: default

steps:
  - name: pubilsh
    image: plugins/docker
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
    settings:
      repo: hub.fengziyu.top/vue
      tags: latest

  - name: deployment
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password   
      script:
        - >
          docker run -d
          --net=web
          --name=vue
          --label="traefik.docker.network=web"
          --label="traefik.enable=true"
          --label="traefik.http.routers.vue-web.rule=Host(\`vue.zhangxiansong.top\`)"
          --label="traefik.http.routers.vue-web.priority=5"
          --label="traefik.http.routers.vue-web.entrypoints=web"
          hub.fengziyu.top/vue  

volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock
