---
kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:13.10.1
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn install

  - name: build
    image: node:13.10.1
    commands:
      - yarn run build