---
kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:13.10.1
    volumes:
      - name: cache
        path: /.yarn-cache
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder /.yarn-cache
      - yarn install

  - name: build
    image: node:13.10.1
    commands:
      - yarn run build

  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password
      target: /data/dockerImage/vue
      source:
        - dist
        - !dist/*.map
        - Dockerfile
        - default.conf
      rm: true

  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password    
      script:
        - cd /data/dockerImage/vue
        - >
          docker build -t vue . &&
          docker rm -f vue &&
          docker run -d
          --net=web
          --name=vue
          --label="traefik.docker.network=web"
          --label="traefik.enable=true"
          --label="traefik.http.routers.hephaestus-web.rule=Host(\`vue.zhangxiansong.top\`)"
          --label="traefik.http.routers.hephaestus-web.priority=5"
          --label="traefik.http.routers.hephaestus-web.entrypoints=web"
          vue

volumes:
  - name: cache
    host:
      path: /data/traefik/.yarn-cache