---
kind: pipeline
type: docker
name: default

steps:
  - name: npm install
    image: node:13.10.1
    volumes:
      - name: cache
        path: .yarn-cache
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install
      - yarn run build
volumes:
  - name: cache
    host:
      path: /data/traefik/.yarn-cache