---
kind: pipeline
type: docker
name: default

steps:
  - name: npm install
    image: node:10.16
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install
      - yarn run build
